### ISSUE TITLE
[BUG] user-select needs prefixes

### ISSUE THREAD

**Issue by slavanga** [30-seconds/30-seconds-of-css#120]
The example for disable selection currently only works in Blink-based browsers.
Other browsers still need vendor prefixes for the user-select property:

```css
-webkit-user-select: none;
   -moz-user-select: none;
    -ms-user-select: none;
        user-select: none;
```

**Comment by atomiks** [comment]
Generally prefixes are avoided because of commonly-used tools like autoprefixer. Notes are added on browser support: 

> ⚠️ Requires prefixes for full support
