### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Bigerfe** [30-seconds/30-seconds-of-css#147]
Excuse me, can I translate this document in Chinese?

**Comment by Chalarangelo** [comment]
@Bigerfe Hi. Translation/localization repositories are not discouraged. If you translate this project and are committed to keeping the translation up to date, comment below with a link at a later time. Might be useful to others as well.

**Comment by Bigerfe** [comment]
Ok, I understand. The expression I just mentioned may not be clear.
I want to translate this document in Chinese https://30-seconds.github.io/30-seconds-of-css/ . Then, can I do this?

**Comment by Bigerfe** [comment]
I will keep the source of the original text and encourage everyone to read the original text. Just want to make more people understand easier.

**Comment by Chalarangelo** [comment]
Same deal. Like I said, you can make a repository and add a translation in it. Drop a link here, if you want.

**Comment by Bigerfe** [comment]
Sorry, I am coming now. As you said, I created a warehouse. Please see this. [https://github.com/Bigerfe/30-seconds-zh](https://github.com/Bigerfe/30-seconds-zh)

**Comment by Bigerfe** [comment]
and...The css part has been translated.

**Comment by Bigerfe** [comment]
Ok I will continue to update

Thank you
