### ISSUE TITLE
[BUG] offscreen snippet links to scetchy/phising website

### ISSUE THREAD

**Issue by cascading-jox** [30-seconds/30-seconds-of-css#162]
I was just going through the different snippets on the website and saw that the snippet Offscreen links to a website which contain some seemingly malicious content (http://pantswebsite.com). What was it originally website supposed to link to and is it possible to change it to something else that is relevant?

**Comment by Chalarangelo** [comment]
Feel free to submit a PR removing the link and we will look into the issue in the meantime. Thanks for bringing this to our attention.
