### ISSUE TITLE
Scam site linked in one of the snippets

### ISSUE THREAD

**Issue by drozumek** [30-seconds/30-seconds-of-css#164]
https://css.30secondsofcode.org/

when you go to the Offscreen snippet, the button link to:
pantswebsite.com -which seems to be hacked/scam website
Please check this out. 

screen:
https://i.imgur.com/q6FtQgU.png

This is not malware from my PC, this shows on different browsers and different computers.

**Comment by skatcat31** [comment]
I don't think it was originally a scam website, but it seems to have been picked up by one. As such we should author a fix.
