### ISSUE TITLE
A (hopefully) better Hamburger Button

### ISSUE THREAD

**Issue by Ranhiru** [30-seconds/30-seconds-of-css#172]
I have created what I think to be a more understandable and cleaner [hamburger menu ](https://css.30secondsofcode.org/snippet/hamburger-button). It doesn't have the jitter on hover that's present in the current snippet.

Just want to see what everyone thinks and if what I've done is better understood and cleaner, I'd be happy to send a PR to update the current snippet.

Current version: https://css.30secondsofcode.org/snippet/hamburger-button
My version: https://codepen.io/duoketchup/pen/NWWVPWO?editors=1100

**Comment by atomiks** [comment]
Great work! Feel free to make a PR

**Comment by Ranhiru** [comment]
Opened PR #173
