### ISSUE TITLE
Add side effect note for the css rules

### ISSUE THREAD

**Issue by Lakshaya-Sood** [30-seconds/30-seconds-of-css#185]
In the file [tile-layout-using-inline-block](https://github.com/30-seconds/30-seconds-of-css/blob/4ba94a7d718c57a7aa34d20405896d5633c41ea9/snippets/tile-layout-using-inline-block.md), parent container element is applied a rule `font-size: 0;` which is doing the magic of [removing spaces between blocks](https://css-tricks.com/fighting-the-space-between-inline-block-elements/#set-the-font-size-to-zero) but that approach has some side effect on various levels.

I suggest adding an info note on the page

**Comment by Chalarangelo** [comment]
Hello,

That sounds like a useful piece of information to provide. Could you submit a PR with the appropriate note? You can add an additional point to the list like `- Note: Explain side effect here`.

**Comment by Lakshaya-Sood** [comment]
Raised a pull request: https://github.com/30-seconds/30-seconds-of-css/pull/186
