### ISSUE TITLE
The preview image in "Image Rotate on Hover" is broken.

### ISSUE THREAD

**Issue by Taimoor0217** [30-seconds/30-seconds-of-css#188]
**Tested Url**
https://www.30secondsofcode.org/css/s/image-hover-rotate

**ScreenShot**
![image](https://user-images.githubusercontent.com/48244930/93908701-64c69600-fd18-11ea-9875-673317e55ac2.png)

**Problem**
The [src url](https://i.picsum.photos/id/669/600/800.jpg) , in the image tag doesnot point to an image anymore.

**Comment by Taimoor0217** [comment]
I would like to work on this.

**Comment by Chalarangelo** [comment]
Sure thing, just change it to another placeholder image from the same site with the same sort of dimensions/aspect ratio. If that site is no longer available, please report back here, we might be in need of a new resource!
