### ISSUE TITLE
Is 30-seconds-of-css not participating in Hacktoberfest?

### ISSUE THREAD

**Issue by Taimoor0217** [30-seconds/30-seconds-of-css#194]

**Comment by Taimoor0217** [comment]
**Details**

Hacktober fest requires, hacktoberfest to be added as a topic in the repository.
The 30-seconds-of-python repo has this added, hoever, 30-seconds-of-css doesnot.

![image](https://user-images.githubusercontent.com/48244930/95015015-14c6c800-0664-11eb-89fb-f20d29d150da.png)

**Comment by Chalarangelo** [comment]
Yep. We [announced yesterday](https://twitter.com/30secondsofcode/status/1312375464590270465?s=20) that only JS and Python repos will be participating, so that we can actually keep up with PRs that are coming in and review them in time.
