### ISSUE TITLE
CSS : Neumorphic Buttons

### ISSUE THREAD

**Issue by crew-guy** [30-seconds/30-seconds-of-css#205]
A simple text-shadow and hover manipulation to get really cool looking design buttons

---

![Neumorphic Design](https://codemyui.com/wp-content/uploads/2020/02/Neumorphic-Button-Click-Hover-and-Clicked-Design.gif)

**Comment by Chalarangelo** [comment]
Duplicate of #203

**Comment by crew-guy** [comment]
Oh wait so so sorry. Completely forgot I had already done this.

### So am I authorized to work on this or not ?
