### ISSUE TITLE
Snippet categories + searching

### ISSUE THREAD

**Issue by atomiks** [30-seconds/30-seconds-of-css#42]
As the list of snippets grows, it will be necessary to categorize them to make them more easily searchable.

Some category ideas I have:

**Layout**
- `Evenly distributed children`
- `Horizontal and vertical centering`
- `Box-sizing reset`
- `Truncate text`
 etc.

**Animation** (possibly even a loaders subcategory)
- `Donut spinner`
- `Hover underline animation`
- `Mouse cursor gradient tracking`
- `Easing variables`
etc

**Interactivity**
- `Disable selection`
- `Popout menu`
- `Hover underline animation` (a snippet can fall under multiple categories)
etc

**Visual**
- `Hairline border`
- `Triangle`
- `System font stack`
- `Gradient text`
- `Etched text`
etc

**Comment by Chalarangelo** [comment]
I definitely like the idea. Something similar to `30-seconds-of-code`'s `tag_database` could work just as well, only difference being the build script needing some changes. I could set up the file and `tagger` system by duping and updating the JS repo's code, then someone else can handle the build process.

**Comment by atomiks** [comment]
Personally I think the tags should be in the files themselves in a comment. This prevents the need to worry about two files when tagging.

**Comment by Chalarangelo** [comment]
The main issue with not using a second file for tags is that it might be difficult to track uncategorized files (or at least it might require more code). However, it's not a huge deal, and it can easily be switched back and forth between a database file and inline tagging, so I think this is gonna be entirely fine even if we somehow decide to change the system later on.
