### ISSUE TITLE
Use Vue for docs?

### ISSUE THREAD

**Issue by atomiks** [30-seconds/30-seconds-of-css#48]
Since some user interactivity is being added, it might be a good idea to make everything more declarative and use components and all other benefits it brings.

Vue can be easily be plugged in to the page without a complex build system, so we don't need to use single file components etc. as that would be overkill.

**Comment by Chalarangelo** [comment]
I think that Vue, much like React, will slow down the page significantly, meaning that when the repo reaches snippet counts well into the hundreds it might be difficult to load on a 3G connection or so. However, I have limited experience with Vue, so it might not be as cumbersome as React. Apart from that, it's probably a cool idea to use Vue as long as the loading times are not significantly slowed down.

**Comment by fejes713** [comment]
I would like to learn Vue too. Have 0 experience with it. If it doesn't slow down the page significantly we could use it.

**Comment by atomiks** [comment]
Don't think there's any point at this stage. Vanilla JS is fine for such a simple page.

**Comment by skatcat31** [comment]
With ES6 imports React no longer requires a build process either. Angular is now the only major frontend framework that must be built that I know of. Between Vue, React, and ES6 modules it should be easy enough to do these features in the future as well

**Comment by skatcat31** [comment]
I'm trying to find the package you need to import to add JSX support to the browser so it'll transpile for you without babel but I'm having a dandy of a time finding it...

**Comment by skatcat31** [comment]
an older example(easily updated) that has some slightly slow performance:

https://www.sitepoint.com/getting-started-react-jsx/

This is because of transpiling in browser. We could also just use `React.createElement()` directly:

https://medium.com/@clmyles/react-without-npm-babel-or-webpack-1e9a6049714
