### ISSUE TITLE
Parcel build

### ISSUE THREAD

**Issue by atomiks** [30-seconds/30-seconds-of-css#7]
Sometimes the `dist/` folder gets created despite `docs/` being specified as the output.

Sometimes more files are generated to `docs/` than there needs to be.

**Comment by Chalarangelo** [comment]
I cannot reproduce the issue on my computer, however I would suggest adding the `dist/` folder to `.gitignore` so that it doesn't get in the way (unless there are plans to actually use said folder, in which case this needs to be sorted out in a different way).

**Comment by atomiks** [comment]
`rimraf` before build in the docs directory solves it.
