### ISSUE TITLE
feat: randomly send code snippet email

### ISSUE THREAD

**Issue by Batur24** [30-seconds/30-seconds-of-css#86]
This repo is quite useful. I am wondering, if have a feature that can send randomly code snippet email to users every day, so that we can learn little by little every day.

Just a thought in mind

Thanks for awesome work!

:)

**Comment by atomiks** [comment]
That would indeed be cool, but I think there needs to be more snippets first before we can do this

**Comment by fejes713** [comment]
@Batur24 We were planning this for quite some time - and you aren't the first one mentioning this.

To me this sounds like the **fantastic** idea, we will definitely make something in the future. 👍

I am closing this now for obvious reasons. Thanks again for showing interest in this!
