### ISSUE TITLE
better code for "Constant width to height ratio" example

### ISSUE THREAD

**Issue by yairEO** [30-seconds/30-seconds-of-css#88]
You don't need the both `::after` & `::after` pseudo elements at all, it is known for centuries that you only need one of them, ans set it to have:

    content: '';
    display: block;
    padding-top: 100%;

**Comment by atomiks** [comment]
The current method ensures content within the element isn't pushed down due to the padding.

**Comment by FarkasJanos** [comment]
Related snippet added here
#114

**Comment by Chalarangelo** [comment]
Seems like this has been resolved and there's a PR with an alternative technique. Closing, move discussion under #114 if necessary.
