### ISSUE TITLE
[FEATURE] "New" icon for new snippets less than 1 month old?

### ISSUE THREAD

**Issue by atomiks** [30-seconds/30-seconds-of-css#99]
This could also apply to the [Code](https://github.com/30-seconds/30-seconds-of-code) and Interviews repos.

Take a look at [Billboard's](https://www.billboard.com/charts/hot-100) sexy SVG icon:

![icons](https://i.gyazo.com/ec81b1ba8789eb3d357933522b808135.png)

**Comment by skatcat31** [comment]
I dislike the gradient due to contrast problems, but I think this is a great idea. It could possibly be confusing though. We might want another badge about newly released features too

**Comment by Chalarangelo** [comment]
`New` snippets was something I wanted to add to 30code for a while. The only issues are that my theorized implementation would probably tag as `new` snippets that have been recently changed (not a problem, that would alert long-time users to anything new in the repo) and that if a PR takes over a month to merge, the files might not be properly tagged. However, with some build diff magic, this could be solved in Travis.

**Comment by skatcat31** [comment]
We could check date of file creation and if date is new enough tag as new?

**Comment by atomiks** [comment]
#104
